// import 'package:flutter/cupertino.dart';
// import 'package:get/get.dart';
// import 'package:get_storage/get_storage.dart';
//
// class LocaLizationClass extends Translations {
//   @override
//   Map<String, Map<String, String>> get keys => {
//         'en_US': {
//           'features': 'Features',
//           'no_service_available':'No services available',
//           'all_field_required':'All fields are required',
//           'select_service':'Select service',
//
//           'particular': 'particular',
//           'professional': 'professional',
//           'email_address': 'E-mail address',
//           'Create_an_account': 'Create an account',
//           'dont_have_account': 'You don\'t have an account ?',
//           'login': 'Login',
//           'forgot_password': 'Forgot password?',
//           'send_code': 'send code',
//           'send_code_at': 'code send at ',
//           'code_not_received':
//               'You can request a new code here you will not receive anything in ',
//           'send_back': 'Send back',
//           'next': 'Next',
//           'Enter_new_password': 'Enter new password',
//           'Enter_old_password': 'Enter old password',
//           'client_instructions': 'Instructions left by the customer',
//           'chooseLanguage': 'Choose Language',
//           'orderhistory': 'Order History',
//           'Confirm_new_password': 'Confirm new password',
//           'Confirm_password': 'Confirm password',
//
//           'create_your_account': 'create your account',
//           'enter_your_number': 'enter your phone number below',
//           'enter_number_msg':
//               'you will receive a text message with a verification code to verify your number',
//           'register_check':
//               'I want to receive health advice from the association tete en l\'air as well as its news',
//
//           'terms_conditions': 'accept the general conditions of use',
//
//           'password': 'Password',
//           "skip": 'Skip',
//           "address": "Enter Address",
//           "Address_Screen_Title": 'My Address',
//           "Profile_Screen_Title": 'My Profile',
//           "Favourite_Screen_Title": 'My Favourites',
//           "MyPoints_Screen_Title": 'My loyalty points',
//           "Payments_Screen_Title": 'My payment method',
//           "Add_payment_method": "Add a payment method",
//           "myPayments": "My Payments",
//           'F.A.Q': 'F.A.Q',
//           'contact_takehair': 'Contact Takehair',
//           'rate_app': 'Rate Takehair on App Store',
//           'research': 'Research',
//           'my_reservation': 'My reservation',
//           'Verification_code': 'Verification code',
//           'summary_of_reservation': 'summary of reservation',
//
//           "service_menu": "service menu",
//           'short_hair': "cheveux courts",
//           'long_hair': "Long hairs",
//           'mats': "Nattes",
//           'when': 'Quand?',
//           'myCurrentPosition': 'Ma position actuelle',
//           'welcome': 'Welcome',
//           'calendar': 'Calendar',
//           'myShowcase': 'My showcase',
//           'myAccount': 'My Account ',
//           'hello_stephane': 'hello',
//           'make_me_transfer': 'make me a transfer',
//           'bankingInfo': 'my banking information',
//
//           'availability': 'Availability',
//           'transfer': 'transfer',
//           'success': 'success',
//           'coming': 'coming',
//           'finished': 'finished',
//           'phone_number': 'Phone number',
//           'my_account': 'Mon compte',
//           'first_name': 'First name',
//           'name': 'Name',
//           'birth_name': 'Birth Name',
//           'company_name': 'Company name',
//
//           'at_my_moms': 'At my moms',
//           'at_my_dads': 'At dad’s',
//           'Add_an_address': 'Add an address',
//           'favorites': 'favorites',
//           'Loyalty': 'Loyalty',
//           'Convert_to_voucher': 'Convert to voucher',
//           'My_cards': 'My cards',
//           'Expired_card': 'Expired card',
//
//           //days
//           'Tuesday': 'Tuesday',
//           'Monday': 'Monday',
//           'Wednesday': 'Wednesday',
//           'Thursday': 'Thursday',
//           'Friday': 'Friday',
//           'Saturday': 'Saturday',
//           'Sunday': 'Sunday',
//
//           //Months
//           'January': 'January',
//           'February': 'February',
//           'March': 'March',
//           'April': 'April',
//           'May': 'May',
//           'June': 'June',
//           'July': 'July',
//           'August': 'August',
//           'September': 'September',
//           'October': 'October',
//           'November': 'November',
//           'December': 'December',
//           'address_client': 'Customer address',
//           'self_transfer': 'I make a transfer of',
//           'sale_available': 'Balance available',
//           'transaction_success':
//               'your transfer has been successfully completed!',
//           'to_login': 'To login',
//           'myBills': 'My Bills',
//           'Haircut': 'Haircut',
//           'Upgrade': 'Upgrade',
//           'Bold': 'Bold',
//           'Outlines': 'Outlines',
//           'Shampoo': 'Shampoo',
//           'To_register': 'To register',
//           'Town': 'Town',
//           'My_address': 'My address',
//           'update': 'Update',
//           'Service_distance': 'Service distance',
//           'schedule_on_off':
//               'Tap the days of the week to turn on/off and change the schedules as you wishes.',
//           'My_professional_photos': 'My professional photos',
//           'Hourly ': 'Hourly ',
//           'Summary_of_the_reservation': 'Summary of the reservation ',
//           'Traveling_expenses': 'Traveling expenses',
//           'Customer_review': 'Customer review',
//           'Change_banking_information': 'Change my banking information',
//           'payment_method': 'Payment method',
//           'start_the_service': 'Start the service',
//           'Completed_the_service': 'End the service',
//           'upload_a_new_photo': 'Upload a new photo',
//           'make_a_photo': 'make a photo',
//           'remove_the_photo': 'remove the photo',
//           'cancel_the_reservation': 'cancel the reservation',
//
//           'orderAmount': 'Order Amount',
//           'admnCommission': 'Admission Commision (20%)',
//           'taxFee': 'Tax Fee (22%)',
//           'proEarning': 'Provider Earning (Excluded tax)',
//           'netEarning': 'Net Earning (Included tax)',
//           'travelFee': 'Travel Fee',
//           'total': 'Total',
//           'prevTrans': 'Transactions',
//           'updatePass': 'Update Password',
//           'logOut': 'LogOut',
//           'areYouSure': 'Are you sure you wants to logout?',
//           'Accountholdername': 'Account holder name',
//           'accNumber': 'Account number',
//           'continue': 'Continue',
//           'cancel': 'Cancel',
//           'sendcode': 'Send code',
//           'verification_request_msg':
//               'Your request to create a new platform is in progress, the process will take a few days',
//           'gotoAddress':'Go to the address'
//         },
//         'fr_FR': {
//           'cancel': 'Annuler',
//           'sendcode': 'envoyer le code ',
//           'no_service_available':'Aucun service disponible',
//           'select_service':'Sélectionnez la prestation',
//           'all_field_required':'Tous les champs sont requis',
//
//           'gotoAddress':'Aller à l\'adresse',
//           'areYouSure': 'Êtes-vous sûr de vouloir vous déconnecter ?',
//           'Accountholdername': 'Nom du titulaire du compte',
//           'accNumber': 'Numéro de compte',
//           'continue': 'Continuer',
//           'updatePass': 'Mettre à jour le mot de passe',
//           'logOut': 'Se déconnecter',
//           'features': 'Features',
//           'Enter_old_password': "Entrez l'ancien mot de passe",
//           'particular': 'particulier',
//           'chooseLanguage': 'Choisissez la langue',
//           'orderhistory': 'Historique des commandes',
//           'professional': 'professionnel',
//           "skip": 'Skip',
//           "address": "Enter Address",
//           'dont_have_account': 'vous n\'avez pas de compte ?',
//           'Create_an_account': 'Creez uu compte',
//           'myBills': 'Mes factures',
//           'login': 'se connecter',
//           'to_login': 'Se connecter',
//           'forgot_password': 'mot de passe oublié?',
//           'send_code': 'envoyer le code',
//           'send_code_at': 'envoyer le code à ',
//           'code_not_received':
//               'Vous pouves demander unuvaus code  ci vouse ne receivez rien dans  ',
//           'Verification_code': 'Code de verification',
//           'send_back': 'renvoyer',
//           'next': 'suivant',
//           'Enter_new_password': 'Entrez un nouveau mot de passe',
//           'Confirm_new_password': 'Confirmer le nouveau mot de passe',
//           'Confirm_password': 'Confirmer mot de passe',
//           'create_your_account': 'Créez votre compte',
//           'enter_your_number': 'enter votre numero de telephoneci- dessouse',
//           'enter_number_msg':
//               'vous recevrez un SMS avec un code de vérification pour vérifier votre numéro',
//           'register_check':
//               'je veux recevoir les conseil sante de l\'association tete en l\'air ainsi que ses aqtualites',
//           'terms_conditions':
//               'l\'accept les conditions generales d\'utilisation!',
//
//           'self_transfer': 'ja me fais un virement de',
//           'sale_available': 'soldie disponible',
//
//           'transaction_success': 'votre virement a ete effectue avec succes',
//           'client_instructions': 'instructions lai sse par le client',
//
//           "Address_Screen_Title": 'Mon adresse',
//           "Profile_Screen_Title": 'Mon profil',
//           "Favourite_Screen_Title": 'Mon préféré',
//           "MyPoints_Screen_Title": 'Mes points de fidélité',
//           "Payments_Screen_Title": 'mes moyens de  paiement',
//           "fidelite": 'Fidelite',
//           "Add_payment_method": "ajouter un moyen de paiement",
//           "myPayments": "My payments",
//           'F.A.Q': 'FAQ',
//           'contact_takehair': 'Contacter Takehair',
//           'rate_app': 'Notez Takehair sur l\'App Storee',
//           'research': 'Research',
//           'my_reservation': 'Mes reservations',
//           "service_menu": "menu des prestation",
//           'short_hair': "cheveux courts",
//           'long_hair': "cheveux long",
//           'mats': "Nattes",
//           'when': 'Quand?',
//           'myCurrentPosition': 'Ma position actuelle',
//           'welcome': 'accueil',
//           'calendar': 'calendrier',
//           'myShowcase': 'ma vitrine',
//           'myAccount': 'Mon compte',
//           'hello_stephane': 'bonjour',
//           'make_me_transfer': 'bonjour stephane',
//           'bankingInfo': 'mes information bancaries',
//
//           'availability': 'Disponibilitie',
//           'transfer': 'je me fais unvirement de',
//           'success': 'votro virement a ete effectue avec success',
//           'coming': 'A venir',
//           'finished': 'terminees',
//           'phone_number': 'numero de telephone',
//           'my_account': 'My account',
//           'first_name': 'prénam',
//           'name': 'nam',
//           'update': 'Update',
//
//           'birth_name': 'nom de naissance',
//           'company_name': 'nom de l\'entreprise',
//
//           'at_my_moms': 'chez maman',
//           'at_my_dads': 'Chez Papa',
//           'Add_an_address': 'Ajouter une adresse',
//           'favorites': 'favoris',
//           'Loyalty': 'fidélité',
//           'Convert_to_voucher': 'convertir en bon d\'achat',
//           'My_cards': 'mes cartes',
//           'Expired_card': 'carte expirée',
//
//           //days
//           'Tuesday': 'mardi',
//           'Monday': 'Lundi',
//           'Wednesday': 'Mercredi',
//           'Thursday': 'Jeudi',
//           'Friday': 'Vendredi',
//           'Saturday': 'Samedi',
//           'Sunday': 'Dimanche',
//
//           //Months
//           'January': 'Janvier',
//           'February': 'février',
//           'March': 'Mars',
//           'April': 'Avril',
//           'May': 'peut',
//           'June': 'Juin',
//           'July': 'Juillet',
//           'August': 'août',
//           'September': 'septembre',
//           'October': 'octobre',
//           'November': 'novembre',
//           'December': 'décembre',
//
//           'Haircut': 'coupe de cheveux',
//           'Upgrade': 'remise à niveau',
//           'Bold': 'Boule à zéro',
//           'Outlines': 'Contours',
//           'Shampoo': 'Shampoing',
//           'To_register': 'Enregistrer',
//           'email_address': 'adresse e-mail',
//           'password': 'Mot de passe',
//           'Town': 'Ville',
//           'My_address': 'Mon addresse',
//           'address_client': 'Addresse du client',
//           'summary_of_reservation': 'recapitulative da reservation',
//
//           'Service_distance': 'distance de prestation',
//           'schedule_on_off':
//               'Appuyez sur les jours de la semaine pour activer/desactiver et changez les horraires comme vous le souhaitez',
//           'My_professional_photos': 'Mes photo professionnelles',
//           'Hourly ': 'horaire ',
//           'Summary_of_the_reservation': 'récapitulatif de la réservation',
//           'Traveling_expenses': 'Frais de déplacement',
//           'Customer_review': 'Avis du client',
//           'Change_banking_information': 'Modifier mes informations bancaires',
//           'Summary_of_the_reservation ': 'récapitulatif de la réservation',
//           'payment_method': 'Mooin de paiement',
//           'start_the_service': 'commencer la prestitaion',
//           'Completed_the_service': 'Terminer la prestitaion',
//           'upload_a_new_photo': 'Charger un nouvelle photo',
//           'make_a_photo': 'rendre un photo',
//           'remove_the_photo': 'retirer la photo',
//           'cancel_the_reservation': 'annular la reservation',
//
//           'verification_request_msg':
//               'Votre demande de création d\'une nouvelle plateforme est en cours, le processus prendra quelques jours',
//         }
//       };
// }
//
// final box = GetStorage();
// LangController langController = Get.put(LangController());
//
// class LangController extends GetxController {
//   void changeLanguage(String param1, String param2) {
//     box.write('langCountry', param1);
//     box.write('langCode', param2);
//     var locate = Locale(param1, param2);
//     Get.updateLocale(locate);
//   }
// }
